spring:
  jpa:
    generate-ddl: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create-drop
    show-sql: 'true'
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5454/foleeHackJunction
    password: password
    hikari:
      auto-commit: false

server:
  error:
    include-message: always
