name: Docker Build and Deploy

on:
  push:
    branches:
      - feature/backend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Packages
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ${{ github.repository_owner }} --password-stdin

      - name: Build and push Docker image
        run: |
          REPO_NAME_LOWERCASE=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          docker build -t docker.pkg.github.com/${{ github.repository_owner }}/$REPO_NAME_LOWERCASE/nesting-solutions-backend:latest -f nesting-solutions-backend/Dockerfile .
          docker push docker.pkg.github.com/${{ github.repository_owner }}/$REPO_NAME_LOWERCASE/nesting-solutions-backend:latest

      - name: Cleanup
        run: docker logout docker.pkg.github.com
